language: python
python:
  - "3.6"
  - "3.6-dev"
  - "3.7"
install:
  - pip install codecov coverage pytest==3.3.2 python_coveralls numpy bytecode

script:
  - python generate_tests.py
  - coverage run --m tests
  - coverage report
  
after_success:
  - codecov
  - coveralls