language: python
python:
  - "3.6"
  - "3.6-dev"
install:
  - pip install codecov coverage pytest-cov python_coveralls numpy

script:
  - python generate_tests.py
  - coverage run --m tests
  - coverage report
  - py.test tests/__init__.py --cov
  
after_success:
  - codecov
  - coveralls