from Redy.Opt import *
from dis import dis


@feature(goto)
def loop1(x):
    task1: label
    task2: label
    end: label

    with task1:
        if x == 'end':
            print('jump end')
            print('jump end')
            print('jump end')
            print('jump end')
            print('jump end')
            print('jump end')
            print('jump end')
            print('jump end')
            print('jump end')
            print('jump end')
            print('jump end')
            print('jump end')
            print('jump end')
            print('jump end')
            print('jump end')
            print('jump end')
            print('jump end')
            print('jump end')
            print('jump end')
            print('jump end')
            print('jump end')
            print('jump end')
            print('jump end')
            print('jump end')

            end.jump()
        elif x == '1':
            print('jump task1')
            print('jump task1')
            print('jump task1')
            print('jump task1')
            print('jump task1')
            print('jump task1')
            print('jump task1')
            print('jump task1')
            print('jump task1')
            print('jump task1')
            print('jump task1')
            print('jump task1')
            print('jump task1')
            print('jump task1')
            print('jump task1')
            print('jump task1')
            print('jump task1')
            print('jump task1')
            print('jump task1')
            print('jump task1')
            print('jump task1')
            print('jump task1')
            print('jump task1')
            print('jump task1')
            print('jump task1')
            print('jump task1')
            print('jump task1')
            print('jump task1')
            print('jump task1')
            print('jump task1')
            print('jump task1')
            print('jump task1')
            print('jump task1')
            print('jump task1')

            task1.jump()
        elif x == '2':
            print('jump task2')
            print('jump task2')
            print('jump task2')
            print('jump task2')
            print('jump task2')
            print('jump task2')
            print('jump task2')
            print('jump task2')
            print('jump task2')
            print('jump task2')
            print('jump task2')
            print('jump task2')
            print('jump task2')
            print('jump task2')
            print('jump task2')
            print('jump task2')
            print('jump task2')
            print('jump task2')
            print('jump task2')
            print('jump task2')
            print('jump task2')
            print('jump task2')
            print('jump task2')
            print('jump task2')
            print('jump task2')
            print('jump task2')
            print('jump task2')
            print('jump task2')
            print('jump task2')
            print('jump task2')
            print('jump task2')
            print('jump task2')
            print('jump task2')
            print('jump task2')
            print('jump task2')
            print('jump task2')
            print('jump task2')
            print('jump task2')
            print('jump task2')
            print('jump task2')
            print('jump task2')
            print('jump task2')
            print('jump task2')
            print('jump task2')
            print('jump task2')
            print('jump task2')
            print('jump task2')
            print('jump task2')
            print('jump task2')
            print('jump task2')

            task2.jump()

        raise ValueError

    task2.mark()
    print('task2| then turn to task1.')
    task1.jump()

    end.mark()
    print('good bye')


dis(loop1)

loop1('1')
loop1('2')
loop1('end')
